// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYHFB-9kvrdGpmA66mAs0UJ5rioXRB-kw',
    appId: '1:811969441336:web:928a27e90485e4e8b780cd',
    messagingSenderId: '811969441336',
    projectId: 'chorequest-cd64a',
    authDomain: 'chorequest-cd64a.firebaseapp.com',
    storageBucket: 'chorequest-cd64a.firebasestorage.app',
    measurementId: 'G-WQC1B23JGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA66AwEG0AMulCqMAfmiYXE7mdE4K3DXls',
    appId: '1:811969441336:android:bf8374c719dda959b780cd',
    messagingSenderId: '811969441336',
    projectId: 'chorequest-cd64a',
    storageBucket: 'chorequest-cd64a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ED6i8H22kNLsLVns1-Y5lQK2V5uVVIo',
    appId: '1:811969441336:ios:3ee4120db4d1300eb780cd',
    messagingSenderId: '811969441336',
    projectId: 'chorequest-cd64a',
    storageBucket: 'chorequest-cd64a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ED6i8H22kNLsLVns1-Y5lQK2V5uVVIo',
    appId: '1:811969441336:ios:3ee4120db4d1300eb780cd',
    messagingSenderId: '811969441336',
    projectId: 'chorequest-cd64a',
    storageBucket: 'chorequest-cd64a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYHFB-9kvrdGpmA66mAs0UJ5rioXRB-kw',
    appId: '1:811969441336:web:2ff6f3b36ad9a3c0b780cd',
    messagingSenderId: '811969441336',
    projectId: 'chorequest-cd64a',
    authDomain: 'chorequest-cd64a.firebaseapp.com',
    storageBucket: 'chorequest-cd64a.firebasestorage.app',
    measurementId: 'G-MEJCRM5Y18',
  );

}